### ISSUE TITLE
HTTP Proxy需要怎么填写？

### ISSUE THREAD

**Issue by linlinlin530** [Xavier-Lam/JAV.bundle#4]
环境：PLEX群晖套件，docker里创建了clash容器，HTTP代理地址192.168.2.128，端口7890，windows测试代理正常。

想请问 "HTTP Proxy" 一栏应该怎么填写？

我测试了 "192.168.2.128:7890" "192.168.2.128" "http://192.168.2.128" "http://192.168.2.128:7890"，好像都没有在yacd里看到connection，但中途好像在填了 "192.168.2.128" 的时候成功走代理刮削出来了一部分标题海报，比较困惑，想请教一下大佬这里应该怎么填是正确的，为啥时好时坏的……

感谢！

**Comment by Xavier-Lam** [comment]
和环境变量HTTP_PROXY的配置一致,
我自己是这样写的 127.0.0.1:10809
