### ISSUE TITLE
Sorry to ask.

### ISSUE THREAD

**Issue by Eilwek** [Xavier-Lam/JAV.bundle#6]
Hi Xavier,

Sorry if I have to ask what seems to be a stupid question - what's the best way to find out what went wrong if all of a sudden the plugin stop working?  If I tried to manually match it will return no result almost instantly.  But everything was working great for months and I didn't upgrade Plex recently.

I tried to match with a different agent and it can work, but I want to keep it consistent and stay with JAV.

Can you let me know where I should start troubleshooting?

**Comment by Xavier-Lam** [comment]
I seemed recently JAVLibrary enabled cloudflare protection (which protects their site from crawlers and robots and needs visitor to complete challenges before visit the site.). I would look into if there are any workarounds to solve this problem, but I am not sure if it can be solved because of Plex's limited ability to run a python script.

Agencies save for JAVLibrary should work as expected.

**Comment by Eilwek** [comment]
Oh I see.  Thank you very much for your reply and explanation.

Now I know why it suddenly stop working.  Please let me know if there's anything I can help or any information you need.

Again, much appreciated your great contribution!

**Comment by Xavier-Lam** [comment]
I updated the agent, you can try to make it work again by following the steps in the [README](https://github.com/Xavier-Lam/JAV.bundle/blob/master/README.md#JAVLibrary). I know it is a bit difficult and the configuration may need to be updated very frequent.

Don't hesitate to ask if you have any questions.

**Comment by Eilwek** [comment]
Hi Xavier, I just followed the instructions and everything works beautifully.

Thank you for your help, I almost thought there will be no solution to the problem.

In the future, if JAVLibrary decides to revert back to no cloudflare, we can just leave the agent and CF field empty right?

**Comment by Xavier-Lam** [comment]
Yes, you can leave the field empty or even leave it with the last value.
