### ISSUE TITLE
目前 JavLibrary 的 cookie 失效太快了，有办法接入flaresolverr么？

### ISSUE THREAD

**Issue by boweic** [Xavier-Lam/JAV.bundle#7]

**Comment by Xavier-Lam** [comment]
由于 plex 插件是在一种 python 2.7 沙盒环境中运行的,因此有很多限制,不能运行完整功能的 python 代码. `flaresolverr` 需要 `Selenium` 和其他依赖,这些依赖无法在该环境中运行(至少很难运行,需要进行大量修改,我还没有看到任何项目这样做). 要么就需要要求用户搭个独立的 "flaresolverr", 不大可能.
我认为获取 `cf_clearance` 的最简单方法是使用 [CF-Clearance-Scraper](https://github.com/Xewdy444/CF-Clearance-Scraper), 我现在也是用这个方案,需要更新的时候跑一下

**Comment by boweic** [comment]
> 由于 plex 插件是在一种 python 2.7 沙盒环境中运行的,因此有很多限制,不能运行完整功能的 python 代码. `flaresolverr` 需要 `Selenium` 和其他依赖,这些依赖无法在该环境中运行(至少很难运行,需要进行大量修改,我还没有看到任何项目这样做). 要么就需要要求用户搭个独立的 "flaresolverr", 不大可能.
> 
> 我认为获取 `cf_clearance` 的最简单方法是使用 [CF-Clearance-Scraper](https://github.com/Xewdy444/CF-Clearance-Scraper), 我现在也是用这个方案,需要更新的时候跑一下

了解，感谢解答。我确实在内网用docker 打了 plex 和 flaresolverr，如有余力也请考虑这种解法。

**Comment by damahala** [comment]
[JAV.bundle.zip](https://github.com/Xavier-Lam/JAV.bundle/files/15173154/JAV.bundle.zip)

You can try this for flaresolverr support if you like. You will need to config "Flare Solverr Url" from JAV Setting. 

Performance-wise, configuring `cf_clearance` seems to be a lot faster than using flaresolverr. 

NOTE: the package is based on the latest code from master with some minor adjustments.
