### ISSUE TITLE
如何手动修改 javlibcom的网址

### ISSUE THREAD

**Issue by dly2345** [Xavier-Lam/JAV.bundle#8]
如何不走代理手动修改提取的网址，或者在https://github.com/javlibcom自动获取新的网址

**Comment by Xavier-Lam** [comment]
https://github.com/Xavier-Lam/JAV.bundle/blob/52e0f11ce5279754fca9cecfa05164cbed240d4e/Contents/Code/agents/javlibrary.py#L27
https://github.com/Xavier-Lam/JAV.bundle/blob/52e0f11ce5279754fca9cecfa05164cbed240d4e/Contents/Code/agents/javlibrary.py#L155
在本地的这两处手动替换网址
但是这个链接依旧没办法绕过cloudflare
